language: node_js
node_js:
- 6.10.0
script:
- npm test
- npm run build
notifications:
  email: false
deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master